### ISSUE TITLE
Location onLocationUpdated not firing

### ISSUE THREAD

**Issue by johnamcruz** [mrmans0n/smart-location-lib#45]
When I have 2 location listeners  (onLocationUpdated method). One on the application and one on the activity. One of the onLocationUpdated method is not firing. Any idea on how to fix this issue?

 SmartLocation.with(getActivity()).location().start(this); (called in a the activity) -- This one is firing the onLocationUpdated method.

 SmartLocation.with(getApplicationContext()).location().start(this); (called in application class) - This one is not called at all.

**Comment by mrmans0n** [comment]
It is like that by design, as the library is not thought to be used in more than one place at the same time: it would add a location callback in the google play services fused location provider two times, and only the last time would remain. 

What I would encourage you to do is change a bit your app so this is not needed: you only need one place where you request the location and from there you can send it internally in any other way. I've used Square's Otto library for this in the past, or GreenDroid's EventBus. Even local intents broadcasted by your own app would be okay.

**Comment by johnamcruz** [comment]
Thank you. I will try that.
