### ISSUE TITLE
Location settings popup if location is disabled.

### ISSUE THREAD

**Issue by anupsarode** [mrmans0n/smart-location-lib#52]
Hello,

Thanks for this awesome library.

Any chance to have the functionality to show Location Settings Dialog if device's location services are disabled?

I found this code provided by Google which does exactly the same. But its too much of code and its redundant to initialize Google Play Services again if to be done manually.

https://github.com/googlesamples/android-play-location/blob/master/LocationSettings/app/src/main/java/com/google/android/gms/location/sample/locationsettings/MainActivity.java

Thanks in advance.

**Comment by mrmans0n** [comment]
It's a cool idea. I will take this into account for a future version, definitely.

**Comment by mindrunner** [comment]
Any news on this? I need to somehow lock down an App as long as location services are disabled. That would be a nice feature.

**Comment by mrmans0n** [comment]
I'm still figuring out how to insert this Google API check for settings, and most probably I would have to break some API compat (so I have to release it in a new major version, which is okay because I'm working in one right now). 

If what you want to check is if the location settings are disabled, you can do it with the current version with the methods exposed by `SmartLocation.with(context).location().state()`. This will be able to check whether they are disabled or not, but what it cannot do is prompt the system to enable them. Would be good enough for locking down the app as you want, though.

**Comment by mindrunner** [comment]
I am using this at the moment calling it in my MainActivity's onResume method. If it returns false, Im gonna show an alert message and redirect the user to location settings. Too easy! Hope to see some thing like this in smart-location-lib soon. Happy to hear that a new major is coming soon! :))

````Java 
public static boolean isLocationEnabled(Context context) {
        int locationMode = 0;
        String locationProviders;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            try {
                locationMode = Settings.Secure.getInt(context.getContentResolver(), Settings.Secure.LOCATION_MODE);
            } catch (Settings.SettingNotFoundException e) {
                e.printStackTrace();
            }
            return locationMode != Settings.Secure.LOCATION_MODE_OFF;
        } else {
            locationProviders = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.LOCATION_PROVIDERS_ALLOWED);
            return !TextUtils.isEmpty(locationProviders);
        }
}
````

**Comment by mrmans0n** [comment]
Actually, the code you just pasted is what's happening in the `.state()` methods I mentioned. It has been that way since a few versions ago, but I suck at documenting and did not put anything about it in the README :(

https://github.com/mrmans0n/smart-location-lib/blob/master/library/src/main/java/io/nlopez/smartlocation/location/utils/LocationState.java

So you could pretty much use it in your code :smile: 

The more in depth support for Play Services (which is not done but probably will in the future) that I was talking about means that the library would launch a dialog to the user to be able to fix whatever requirement is not being fulfilled for the selected location request. Kind of what Google Maps does if you don't have the WiFi enabled, for example.

**Comment by mindrunner** [comment]
Aaah, now I got it! Nice. Yeah just fixed up my code. Good job! Keep going
buddy.

**Comment by mrmans0n** [comment]
@anupsarode I have just uploaded the support for this in the snapshot version. It seems to work, so this will be part of the 3.2.0 version of the library. I will close this issue now :)

**Comment by anupsarode** [comment]
@mrmans0n - Awesome :)
