### ISSUE TITLE
Geofencing Questions

### ISSUE THREAD

**Issue by adfleshner** [mrmans0n/smart-location-lib#56]
I have a few questions about the geofencing. I was unsure if the radius parameter is the same as the google play services radius which I believe is meters ( I maybe wrong ). I was testing geofencing driving around the city going into fences. I setup a map and with Circles on it and would drive into those circles and nothing would kick off telling me whether I had entered or exited the geofence ( the enter and the exit radius are the same if that is a problem that can be changed. ) But while I was walking around my home the tells me i entered the my home geo fence but all of them around the city were not working. Also for best results what is a good radius to set? Thank you for your time.

**Comment by mrmans0n** [comment]
I found a bug which prevented the radius to be set in the actual geofencing model. I will solve this asap and you will be getting consistent results.

As for the best values, around 100-150 m would be best because you don't need very exact positions usually and they are fairly quick to get with that range.
